blog/urls.py
from django.urls import path

from blog.views import CategoryPostView, IndexView, PostDetailView, CategoryListView, TagListView, TagPostView

app_name = 'blog'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('category/<str:category_slug>/',
         CategoryPostView.as_view(), name='category_post'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
]

youtube_materials/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)
    image = models.ImageField(
        upload_to='post_images/', null=True, blank=True
    )

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class VideoInfo(models.Model):
    title =  models.CharField(max_length=255)
    description = models.TextField()
    channel_id = models.CharField(max_length=255)
    channel_name = models.CharField(max_length=255)
    thumbnail = models.CharField(max_length=255)
    video_published_date = models.DateTimeField

blog/views.py
from django.shortcuts import get_object_or_404

from django.db.models import Count, Q
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from blog.models import Post, Category, Tag


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'


class CategoryListView(ListView):
    queryset = Category.objects.annotate(
        num_posts=Count('post', filter=Q(post__is_public=True))
    )


class TagListView(ListView):
    queryset = Tag.objects.annotate(
        num_posts=Count('post', filter=Q(post__is_public=True))
    )

class CategoryPostView(ListView):
    model = Post
    template_name = 'blog/category_post.html'

    def get_query_set(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class TagPostView(ListView):
    model = Post
    template_name = 'blog/tag_post.html'

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context

blog/templates/blog/category_list.html
<!-- blog/category_list.html -->

<h1>カテゴリ一覧</h1>
<ul>
  {% for category in object_list %}
  <li><a href="{% url 'blog:category_post' category.slug %}"></a>{{ category.name }} ({{ category.num_posts }})</li>
  {% empty %}
  <li>カテゴリはありません。</li>
  {% endfor %}
</ul>

blog/templates/blog/category_post.html
<!-- blog/category_post.html -->

<h1>カテゴリ「{{ category.name }}」の投稿一覧</h1>
<ul>
  {% for post in object_list %}
  {% if user.is_authenticated or post.is_public %}
  <li>{% if not post.is_public %}[下書き] {% endif %}<a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></li>
  {% else %}
  <li>投稿はありません。</li>
  {% endif %}
  {% empty %}
  <li>まだ投稿はありません。</li>
  {% endfor %}
</ul>

blog/templates/blog/index.html
<!-- blog/index.html -->

<h1>投稿一覧</h1>
<ul>
    {% for post in object_list %}
    {% if user.is_authenticated or post.is_public %}
    <li>{% if not post.is_public %}[下書き] {% endif %}<a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</li>
    {% endif %}
    {% empty %}
    <li>また投稿はありません。</li>
    {% endfor %}
</ul>

blog/templates/blog/post_detail.html
<!-- blog/post_detail.html -->

<h1>{{ object.title }}</h1>
<p>{{ object.published_at|date }}</p>
<p>{{ object.category.name }}</p>
{% for tag in object.tags.all %}
{{ tag.name }}
{% endfor %}
<hr>
{{ object.content|safe }}

blog/templates/blog/tag_list.html
<!-- blog/tag_list.html -->

<h1>タグ一覧</h1>
<ul>
  {% for tag in object_list %}
  <li><a href="{% url 'blog:tag_post' tag.slug %}"></a>{{ tag.name }} ({{ tag.num_posts }})</li>
  {% empty %}
  <li>タグはありません。</li>
  {% endfor %}
</ul>

blog/templates/blog/tag_post.html
<!-- blog/tag_post.html -->

<h1>「#{{ tag.name }}」の投稿一覧</h1>
<ul>
  {% for post in object_list %}
  {% if user.is_authenticated or post.is_public %}
  <li>{% if not post.is_public %}[下書き] {% endif %}<a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></li>
  {% else %}
  <li>投稿はありません。</li>
  {% endif %}
  {% empty %}
  <li>まだ投稿はありません。</li>
  {% endfor %}
</ul>